version: '3'

vars:

tasks:
  swagger-generate:
    desc: "Generate API Swagger documentation from code"
    cmds:
      - swag init --dir internal/delivery/rest/v1 -g root.go -o internal/delivery/rest/v1/docs # v1

  swagger-fmt:
    desc: "Format Swagger documentation comments in code"
    cmds:
      - swag fmt
